GesRes/urls.py
from django.conf import settings
from django.conf.urls.static import static


"""
URL configuration for empleado project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from applications.home. views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin-empleados'),
    path('home/', include('applications.home.urls')), 
    #siempre que queramos mostrar un template en urls, debemos ponerle el .as_view() o include
    path('empleado/', include('applications.empleado.urls')),
    path('departamento/', include('applications.departamento.urls')),
    path('stock/', include('applications.stock.urls')),
    path('', include('applications.produccion.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/urls.py
from django.urls import path
from . import views


app_name = 'departamento_app'
urlpatterns = [
    path('list-all-departamentos', 
         views.DepartamentoListAllView.as_view(), 
         name='all_departamentos'),
    path('create-departamento/', 
         views.DepartamentoCreateView.as_view(), 
         name='create-departamento'),
    path('eliminar-departamento/<pk>', 
         views.DepartamentoDeleteView.as_view(), 
         name='delete-departamento'),
    path('update-empleado/<pk>', 
         views.DepartamentoUpdateView.as_view(), 
         name='departamento-update'),
]

applications/empleado/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'persona_app'

urlpatterns = [
    path('', 
        views.InicioView.as_view(),
          name='Inicio'),
    path('empleados-all/', 
         views.ListAllEmpleado.as_view(),
          name='empleados_all'),
    path('add-empleado/', 
         views.EmpleadoCreateView.as_view(),
          name='add_empleado'),
    path('success/', 
         views.SuccessView.as_view(),
          name='correcto',),
    path('update-empleado/<pk>', 
         views.EmpleadoUpdateView.as_view(), 
         name='modificar_empleado'),
    path('delete-empleado/<pk>', 
         views.EmpleadoDeleteView.as_view(), 
         name='eliminar_empleado'),
    path('ver_empleado/<pk>', 
         views.EmpleadoDetailView.as_view(), 
         name='ver-empleado'),
    path('empleados_by_departamento/<name>', 
         views.EmpleadoByAreaListView.as_view(), 
         name='empleados-by-area'),
    path('dashboard/', 
         views.EmpleadoDashboardView.as_view(), 
         name='mostrar-dashboard'),
    path('crear_habilidad/', 
         views.CrearHabilidadView.as_view(), 
         name='crear-habilidad'),
    path('crear_trabajo/', 
         views.CrearTrabajoView.as_view(), 
         name='crear-trabajo'),
    path('mostrar_puestos/', 
         views.ListAllTrabajos.as_view(), 
         name='mostrar-puestos'),
    path('eliminar_puesto/<pk>', 
         views.TrabajoDeleteView.as_view(), 
         name='eliminar-puesto'),
    path('empleados_portrabajo/<puesto>', 
         views.EmpleadoByTrabajoListView.as_view(), 
         name='empleados-por-trabajo'),
    path('update-trabajo/<pk>', 
         views.TrabajoUpdateView.as_view(), 
         name='update-trabajo'),
]

applications/produccion/urls.py
from django.urls import path
from . import views

app_name = 'produccion_app'

urlpatterns = [
    # ---------- Path Varios -----------#

        path('', 
            views.inicioView.as_view(), 
            name='Inicio'),

        path('success_url', 
            views.SuccessView.as_view(),
            name='success'),

        path('dashboard/',
             views.ProduccionDashboardView.as_view(),
             name='dashboard'),

    # ----- Path Producción ----- #

        path('lista_all_produccion/', 
            views.ProduccionListView.as_view(),
            name='all_produccion'),

        path('create_produccion/',
            views.ProduccionCreateView.as_view(),
            name='create_produccion'),
        
        path('anulate_producion/<pk>/',
             views.ProduccionAnulateView.as_view(),
             name='anulate_produccion'),

        path('detail_produccion/<pk>/',
             views.ProduccionDetailView.as_view(),
             name='detail_produccion'),
             
    # ----- Path Receta ----- #

        path('lista_all_receta/',
            views.RecetaListView.as_view(),
            name='all_receta'),
        
        path('create_receta/',
            views.RecetaCreateView.as_view(),
            name='create_receta'),

        path('detail_receta/<pk>/',
             views.RecetaDetailView.as_view(),
             name='detail_receta'),

        path('delete-receta/<pk>/',
             views.RecetaDeleteView.as_view(),
             name='delete_receta'),

        path('update_receta/<pk>/',
             views.RecetaUpdateView.as_view(),
             name='update_receta'),
             
    # ----- Path Ingredientes Receta ----- #

        path('create_ingredientes_receta/<pk>',
            views.IngredientesRecetaCreateView.as_view(),
            name='create_ingredientes_receta'),
        
        path('delete_ingredientes_receta/<pk>',
             views.IngredientesRecetaDeleteView.as_view(),
             name='delete_ingredientes_receta'),

        path('update_ingredientes_receta/<pk>',
             views.IngredientesRecetaUpdateView.as_view(),
             name='update_ingredientes_receta'),
            ]
        

applications/stock/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'stock_app'

urlpatterns = [
    # ---------- Path Varios -----------#
     path('', 
          views.InicioView.as_view(), 
          name='Inicio'),

     path('success_url', 
          views.SuccessView.as_view(), 
          name='success'),
     
     path('dashboard/',
          views.StockDashboardView.as_view(),
          name='dashboard'),
     

     # ----- Path Productos ----- #
     
     path('lista_all_productos/', 
          views.ProductoListView.as_view(), 
          name='all_productos'),

     path('add-producto/', 
          views.ProductoCreateView.as_view(), 
          name='add_producto'),

     path('productos/clasificacion/<clasificacion_id>/', 
          views.ProductoListView.as_view(), 
          name='productos_por_clasificacion'),

     path('delete-producto/<pk>/',
          views.ProductoDeleteView.as_view(),
          name='delete_producto'),
     
     path('update-producto/<pk>/',
          views.ProductoUpdateView.as_view(),
          name='update_producto'),

     path('detail-producto/<pk>/',
          views.ProductoDetailView.as_view(),
          name='detail_producto'),

     # -------- Path Proveedores --------- #

     path('lista_all_proveedores/', 
          views.ProveedorListView.as_view(), 
          name='all_proveedores'),
     
     path('add-proveedor/', 
          views.ProveedorCreateView.as_view(),
          name='add_proveedor'),

     path('delete-proveedor/<pk>',
          views.ProveedorDeleteView.as_view(),
          name='delete_proveedor'),
     
     path('update-proveedor/<pk>',
          views.ProveedorUpdateView.as_view(),
          name='update_proveedor'),
     
     path('detail-proveedor/<pk>',
          views.ProveedorDetailView.as_view(),
          name='detail_proveedor'),

     # ------ Path Clasificaciones ------ #

     path('lista_all_clasificaciones/',
          views.ClasificacionListView.as_view(),
          name='all_clasificaciones'),
     
     path('add-clasificacion',
          views.ClasificacionCreateView.as_view(),
          name='add_clasificacion'),

     path('delete-clasificacion/<pk>',
          views.ClasificacionDeleteView.as_view(),
          name='delete_clasificacion'),
     
     path('update-clasificacion/<pk>',
          views.ClasificacionUpdateView.as_view(),
          name='update_clasificacion'),
     
     # -------- Path Compra --------- #

     path('add-compra/<pk>/',
          views.CompraCreateView.as_view(),
          name='add_compra'),

     path('lista_all_compras/',
          views.CompraListView.as_view(),
          name='all_compras'),
     
     path('anulate-compra/<pk>/',
          views.CompraAnulateView.as_view(),
          name='anulate_compra'),
     
     path('detail-compra/<pk>/',
          views.CompraDetailView.as_view(),
          name='detail_compra'),

     # -------- Path Consumo --------- #

     path('add-consumo/<pk>/',
          views.ConsumoCreateView.as_view(),
          name='add_consumo'),
     
     path('lista_all_consumos/',
          views.ConsumoListView.as_view(),
          name='all_consumos'),
     
     path('anulate-consumo/<pk>/',
          views.ConsumoAnulateView.as_view(),
          name='anulate_consumo'),
     
     path('detail-consumo/<pk>/',
          views.ConsumoDetailView.as_view(),
          name='detail_consumo'),
     ]

templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="menu" data-dropdown-menu>
      {# Quitamos menu-text del li y lo dejamos solo como un item fuerte #}
      <li style="font-weight: bold;">
        <a href="{% url 'persona_app:Inicio' %}" style="color: #0a4d8c;">GesRes RH</a>
      </li>
      <li><a href="{% url 'persona_app:empleados_all' %}">Empleados</a></li>
      <li><a href="{% url 'departamento_app:all_departamentos' %}">Departamentos</a></li>
      <li><a href="{% url 'persona_app:mostrar-puestos' %}">Puestos</a></li>
      <li><a href="{% url 'persona_app:mostrar-dashboard' %}">Dashboard</a></li>
      <li><a href="/admin">Admin</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><a href="{% url 'persona_app:mostrar-dashboard' %}" class="button small" style="margin-bottom: 0; margin-left: 10px;">
        DASHBOARD
      </a></li>
    </ul>
  </div>
</div>

templates/includes/header2.html
<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu align-left align-middle" data-dropdown-menu>
      
      <li>
        <a href="{% url 'stock_app:Inicio' %}" 
           style="color: #0a4d8c" 
           class="menu-text">
           GesRes Stock
        </a>
      </li>

      <li class="has-submenu">
        <a href="{% url 'stock_app:all_productos' %}">Materia Prima</a>
        
        <ul class="submenu menu vertical" data-submenu>

          {% for clasificacion in clasificaciones_menu %}
            {% if clasificacion.nombre != "Otros varios" %}
              <li>
                <a href="{% url 'stock_app:productos_por_clasificacion' clasificacion.id %}">
                  {{ clasificacion.nombre }}
                </a>
              </li>
            {% endif %}
          {% empty %}
            <li>
              <span style="padding: 10px; display: block;">
                No hay clasificaciones
              </span>
            </li>
          {% endfor %}

          {% for clasificacion in clasificaciones_menu %}
            {% if clasificacion.nombre == "Otros varios" %}
              <li>
                <a href="{% url 'stock_app:productos_por_clasificacion' clasificacion.id %}">
                  {{ clasificacion.nombre }}
                </a>
              </li>
            {% endif %}
          {% endfor %}

        </ul>
      </li>

      <li>
        <a href="{% url 'stock_app:all_clasificaciones' %}">
          Clasificaciones
        </a>
      </li>

      <li>
        <a href="{% url 'stock_app:all_proveedores' %}">
          Proveedores
        </a>
      </li>
      <li class="has-submenu">
        <a>Transacciones</a>
        
        <ul class="submenu menu vertical" data-submenu>
              <li>
                <a href="{% url 'stock_app:all_compras' %}">
                  Compras
                </a>
              </li>
              <li>
                <a href="{% url 'stock_app:all_consumos' %}">
                  Consumos
                </a>
              </li>
        </ul>

      <li>
        <a href="{% url 'stock_app:dashboard' %}">Dashboard</a>
      </li>
      <li>
        <a href="{% url 'produccion_app:Inicio' %}">Ir a Producción</a>
      </li>
    </ul>
  </div>
</div>

templates/includes/header3.html
<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu align-left align-middle" data-dropdown-menu>
      <li>
        <a href="{% url 'produccion_app:Inicio' %}"
           style="color: #0a4d8c"
           class="menu-text">
           GesRes Producción
        </a>
      </li>
      <li>
        <a href="{% url 'produccion_app:all_produccion' %}">Operaciones</a>
      </li>
      <li>
        <a href="{% url 'produccion_app:all_receta' %}">Recetas</a>
      </li>
      <li>
        <a href="{% url 'produccion_app:dashboard' %}">Dashboard</a>
      </li>
      <li>
        <a href="{% url 'stock_app:Inicio' %}">Volver a Stock</a>
      </li>
    </ul>
  </div>
</div>