GesRes/urls.py
from django.conf import settings
from django.conf.urls.static import static


"""
URL configuration for empleado project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from applications.home. views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin-empleados'),
    path('home/', include('applications.home.urls')), 
    #siempre que queramos mostrar un template en urls, debemos ponerle el .as_view() o include
    path('empleado/', include('applications.empleado.urls')),
    path('departamento/', include('applications.departamento.urls')),
    path('stock/', include('applications.stock.urls')),
    path('', include('applications.produccion.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/stock/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'stock_app'

urlpatterns = [
    # ---------- Path Varios -----------#
     path('', 
          views.InicioView.as_view(), 
          name='Inicio'),

     path('success_url', 
          views.SuccessView.as_view(), 
          name='success'),
     
     path('dashboard/',
          views.StockDashboardView.as_view(),
          name='dashboard'),
     

     # ----- Path Productos ----- #
     
     path('lista_all_productos/', 
          views.ProductoListView.as_view(), 
          name='all_productos'),

     path('add-producto/', 
          views.ProductoCreateView.as_view(), 
          name='add_producto'),

     path('productos/clasificacion/<clasificacion_id>/', 
          views.ProductoListView.as_view(), 
          name='productos_por_clasificacion'),

     path('delete-producto/<pk>/',
          views.ProductoDeleteView.as_view(),
          name='delete_producto'),
     
     path('update-producto/<pk>/',
          views.ProductoUpdateView.as_view(),
          name='update_producto'),

     path('detail-producto/<pk>/',
          views.ProductoDetailView.as_view(),
          name='detail_producto'),

     # -------- Path Proveedores --------- #

     path('lista_all_proveedores/', 
          views.ProveedorListView.as_view(), 
          name='all_proveedores'),
     
     path('add-proveedor/', 
          views.ProveedorCreateView.as_view(),
          name='add_proveedor'),

     path('delete-proveedor/<pk>',
          views.ProveedorDeleteView.as_view(),
          name='delete_proveedor'),
     
     path('update-proveedor/<pk>',
          views.ProveedorUpdateView.as_view(),
          name='update_proveedor'),
     
     path('detail-proveedor/<pk>',
          views.ProveedorDetailView.as_view(),
          name='detail_proveedor'),

     # ------ Path Clasificaciones ------ #

     path('lista_all_clasificaciones/',
          views.ClasificacionListView.as_view(),
          name='all_clasificaciones'),
     
     path('add-clasificacion',
          views.ClasificacionCreateView.as_view(),
          name='add_clasificacion'),

     path('delete-clasificacion/<pk>',
          views.ClasificacionDeleteView.as_view(),
          name='delete_clasificacion'),
     
     path('update-clasificacion/<pk>',
          views.ClasificacionUpdateView.as_view(),
          name='update_clasificacion'),
     
     # -------- Path Compra --------- #

     path('add-compra/<pk>/',
          views.CompraCreateView.as_view(),
          name='add_compra'),

     path('lista_all_compras/',
          views.CompraListView.as_view(),
          name='all_compras'),
     
     path('anulate-compra/<pk>/',
          views.CompraAnulateView.as_view(),
          name='anulate_compra'),
     
     path('detail-compra/<pk>/',
          views.CompraDetailView.as_view(),
          name='detail_compra'),

     # -------- Path Consumo --------- #

     path('add-consumo/<pk>/',
          views.ConsumoCreateView.as_view(),
          name='add_consumo'),
     
     path('lista_all_consumos/',
          views.ConsumoListView.as_view(),
          name='all_consumos'),
     
     path('anulate-consumo/<pk>/',
          views.ConsumoAnulateView.as_view(),
          name='anulate_consumo'),
     
     path('detail-consumo/<pk>/',
          views.ConsumoDetailView.as_view(),
          name='detail_consumo'),
     ]

applications/stock/models.py
from decimal import Decimal

from django.db import models, transaction
from django.core.validators import MinValueValidator
from django.forms import ValidationError
from .managers import ProductoManager, ClasificacionManager, ProveedorManager, CompraManager, ConsumoManager
# Create your models here.


#--------------- Clasificacion Model -----------------#
class Clasificacion(models.Model):
    nombre = models.CharField(max_length=50, 
                              unique=True)
    objects = ClasificacionManager()

    class Meta:
        ordering = ['nombre']
    
    def __str__(self):
        return self.nombre
    
# --------------- Proveedor Model --------------- #

class Proveedor(models.Model):
    nombre = models.CharField(max_length=50)
    num_contacto = models.CharField(max_length=20)  
    email = models.EmailField(max_length=254)
    activo = models.BooleanField(default=True)
    direccion = models.CharField(max_length=50, 
                                 blank=True)
    objects = ProveedorManager()

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return self.nombre

#---------------- Producto Model -------------------#

class Producto(models.Model):
    TIPO_CHOICES = (
        ('MP', 'Materia Prima'),
        ('PT', 'Producto Terminado'),
        ('SC', 'Sin Clasificar'),
    )
    tipo = models.CharField(max_length=2, 
                            choices=TIPO_CHOICES,
                            default='SC'
                            )
    nombre = models.CharField(max_length=50, 
                              unique=True)
    precio = models.DecimalField (max_digits=10, 
                                  decimal_places=2, 
                                  validators = [MinValueValidator(0)],
                                  default=0
                                  )
    proveedor = models.ForeignKey(Proveedor, 
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  blank=True)
    clasificacion = models.ForeignKey(Clasificacion, 
                                      on_delete=models.SET_NULL,
                                      null=True,
                                      blank=True)
    stock_actual = models.DecimalField(default=0,
                                       decimal_places=2,
                                       max_digits=10,
                                       validators = [MinValueValidator(0)]
                                       )
    stock_minimo = models.DecimalField(default=0, 
                                       decimal_places=2,
                                       max_digits=10,
                                       help_text='cantidad minima antes de disparar alerta',
                                       validators = [MinValueValidator(0)]
                                       )
    descripcion = models.TextField(blank=True)
    objects = ProductoManager()
    
    @property
    def costo_calculado(self):
        if self.tipo != 'PT':
            return self.precio

        # Si no tiene receta todavía
        if not hasattr(self, 'receta'):
            return 0

        return sum(
            ingrediente.cantidad * ingrediente.producto.precio
            for ingrediente in self.receta.ingredientes.all()
        )

    #validacion para dar consistencia
    def clean(self):
        if self.tipo == 'PT' and self.precio != 0:
            raise ValidationError({
                'precio': 'Un Producto Terminado no debe tener precio manual.'
            })

        if self.tipo == 'MP' and self.precio <= 0:
            raise ValidationError({
                'precio': 'La Materia Prima debe tener un precio mayor a 0.'
            })

    class Meta:
        ordering = ['nombre']
        
    def __str__(self):
        return f'{self.nombre}'
    

# ---------------- Compra Model -------------------#

class Compra(models.Model):
    
    producto = models.ForeignKey(Producto,
                                 on_delete=models.PROTECT,
                                 limit_choices_to={'tipo': 'MP'},
                                 related_name='compras')
    
    cantidad = models.DecimalField(
        max_digits=10, 
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))]
        ) 
    
    total_pagado = models.DecimalField(
        max_digits=10, 
        decimal_places=2)

    fecha = models.DateTimeField(auto_now_add=True)

    objects = CompraManager()

    def clean(self):
        if self.cantidad <= 0:
            raise ValidationError('La cantidad debe ser mayor a 0.')

    def save(self, *args, **kwargs):

        if not self.pk:
            with transaction.atomic():

                producto = Producto.objects.select_for_update().get(pk=self.producto.pk)

                self.total_pagado = producto.precio * self.cantidad

                producto.stock_actual += self.cantidad
                producto.save()

        super().save(*args, **kwargs)
    
    def anular(self):
        with transaction.atomic():
            producto = Producto.objects.select_for_update().get(pk=self.producto.pk)

            if self.cantidad > producto.stock_actual:
                raise ValidationError("Stock inconsistente.")

            producto.stock_actual -= self.cantidad
            producto.save()

            self.delete()
            
# ---------------- Consumo Model ------------------- #

class Consumo(models.Model):
    producto = models.ForeignKey(Producto,
                                 limit_choices_to={'tipo': 'PT'},
                                 on_delete=models.PROTECT,
                                 related_name='consumos')
    cantidad = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(0.01)]
)

    fecha = models.DateTimeField(auto_now_add=True)

    motivo = models.CharField(max_length=75,
                               blank=True,
                               help_text='Motivo del consumo, ej: venta, muestra, etc.'
                               )
    objects = ConsumoManager()
    
    def __str__(self):
        return f'{self.producto.nombre} - {self.cantidad}'

    # ------------- Metodo Clean ------------ #
    def clean(self):
        if self.cantidad <= 0:
            raise ValidationError('La cantidad debe ser mayor a 0.')
    
    # ------------- Metodo Save ------------ #
    def save(self, *args, **kwargs):

        self.full_clean()

        if not self.pk:
            with transaction.atomic():
                
                # accedemos al prodcto y restamos stock.
                producto = Producto.objects.select_for_update().get(pk=self.producto.pk)

                if self.cantidad > producto.stock_actual:
                    raise ValidationError(
                        f"No hay stock suficiente. Stock actual: {producto.stock_actual}"
                    )

                producto.stock_actual -= self.cantidad
                producto.save()

        super().save(*args, **kwargs)
    
    # ------------- Metodo Anulate ------------ #
    def anular(self):
        with transaction.atomic():
            producto = Producto.objects.select_for_update().get(pk=self.producto.pk)

            producto.stock_actual += self.cantidad
            producto.save()

            self.delete()

applications/stock/forms.py
from .models import Producto, Proveedor, Clasificacion, Compra, Consumo
from django import forms



#------- Form de Producto ----------#
class ProductoForm(forms.ModelForm):
    """Form definition for Producto."""

    class Meta:
        """Meta definition for Productoform."""

        model = Producto
        fields = (
            'nombre',
            'tipo',
            'precio',
            'proveedor',
            'clasificacion',
            'stock_actual',
            'stock_minimo',
            'descripcion',
        )

#------------ Form de Proveedor -----------#
class ProveedorForm(forms.ModelForm):
    """Form definition for Proveedor."""

    class Meta:
        """Meta definition for Proveedorform."""

        model = Proveedor
        fields = ('__all__')

#---------Form de Clasificacion ------------#
class ClasificacionForm(forms.ModelForm):
    """Form definition for Clasificacion."""

    class Meta:
        """Meta definition for Clasificacionform."""

        model = Clasificacion
        fields = ('nombre',)

# ---------------- Form de Compra ------------------#
class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = (
            'cantidad',
        )
        

# ---------------- Form de Consumo ------------------#
class ConsumoForm(forms.ModelForm):
    class Meta:
        model = Consumo
        fields = (
            'cantidad',
            'motivo',
        )

templates/stock/detail_producto.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {% include 'includes/header2.html' %}

  <div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
      <div class="cell small-12 medium-8 large-6">

        <h2 class="text-center" style="margin: 1.5rem 0;">Detalle - {{ object.nombre }}</h2>

        <div class="callout secondary shadow">
          <ul class="vertical menu">
            <li>
              <label><strong>Nombre</strong></label>
              <p class="no-margin-bottom">{{ object.nombre }}</p>
            </li>
            <li>
              <label><strong>Tipo</strong></label>
              <p class="no-margin-bottom">{{ object.get_tipo_display }}</p>
            </li>
            <li>  
              <label><strong>Precio</strong></label>
              <p class="no-margin-bottom">{{ object.costo_calculado|floatformat:1 }} UYU | xkg</p>
            </li>
            <li>
              <label><strong>Proveedor</strong></label>
              <p class="no-margin-bottom">{{ object.proveedor }}</p>
            </li>
            <li>
              <label><strong>Clasificación</strong></label>
              <p class="no-margin-bottom">{{ object.clasificacion }}</p>
            </li>
            <li>
              <label><strong>Stock Actual</strong></label>
              <p class="no-margin-bottom">{{ object.stock_actual }} kg</p>
            </li>
            <li>
              <label><strong>Stock Mínimo</strong></label>
              <p class="no-margin-bottom">{{ object.stock_minimo }} kg</p>
            </li>
            <li>
              <label><strong>Descripción</strong></label>
              <p class="no-margin-bottom">{{ object.descripcion|default:"-" }}</p>
            </li>
          </ul>
        </div>

        <div class="button-group align-center" style="margin-top: 1.5rem;">
          <a href="{% url 'stock_app:update_producto' object.id %}" class="button success" style="margin-right:10px;">Editar</a>
          <a href="{% url 'stock_app:delete_producto' object.id %}" class="button alert" style="margin-right:10px;">Eliminar</a>
          <a href="{% url 'stock_app:all_productos' %}" class="button secondary">Volver</a>
        </div>

      </div>
    </div>
  </div>

{% endblock content %}

templates/stock/detail_proveedor.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {% include 'includes/header2.html' %}

  <div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
      <div class="cell small-12 medium-8 large-6">

        <h2 class="text-center" style="margin: 1.5rem 0;">Detalle - {{ object.nombre }}</h2>

        <div class="callout secondary shadow">
          <ul class="vertical menu">
            <li>
              <label><strong>Nombre</strong></label>
              <p class="no-margin-bottom">{{ object.nombre }}</p>
            </li>
            <li>
              <label><strong>Contacto</strong></label>
              <p class="no-margin-bottom">{{ object.num_contacto }}</p>
            </li>
            <li>
              <label><strong>Email</strong></label>
              <p class="no-margin-bottom">{{ object.email }}</p>
            </li>
            <li>
              <label><strong>Activo</strong></label>
              <p class="no-margin-bottom">{% if object.activo %}Sí{% else %}No{% endif %}</p>
            </li>
            <li>
              <label><strong>Dirección</strong></label>
              <p class="no-margin-bottom">{{ object.direccion|default:"-" }}</p>
            </li>
          </ul>
        </div>

        <div class="button-group align-center" style="margin-top: 1.5rem;">
          <a href="{% url 'stock_app:update_proveedor' object.id %}" class="button success" style="margin-right:10px;">Editar</a>
          <a href="{% url 'stock_app:delete_proveedor' object.id %}" class="button alert" style="margin-right:10px;">Eliminar</a>
          <a href="{% url 'stock_app:all_proveedores' %}" class="button secondary">Volver</a>
        </div>

      </div>
    </div>
  </div>

{% endblock content %}

templates/stock/list_all_compra.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/header2.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x">
    <div class="cell small-12">

      <h2 class="text-center" style="margin: 1.5rem 0;">
        Listado de Compras
      </h2>
      <form method="get" class="grid-x grid-margin-x">

        <div class="cell large-8">
          <input type="text" name="kword" id="kword" placeholder="Buscar por Nombre de la materia">
          <div class="grid-x grid-margin-x align-bottom">
            <div class="cell medium-9">
              <input type="date" name="fecha" id="fecha" placeholder="Buscar por Fecha"
                class="no-margin-bottom">
            </div>
            <div class="cell medium-3">
              <button
                type="submit"
                class="button success expanded"
                style="height: 39px;">
                Buscar
              </button>
            </div>
          </div>
        </div>
      </form>

      <table class="hover unstriped">
        <thead>
          <tr>
            <th width="50">ID</th>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Proveedor</th>
            <th>Precio Total</th>
            <th>Fecha</th>
            <th width="150" class="text-center">Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for compra in object_list %}
          <tr>
            <td>{{ compra.id }}</td>
            <td>{{ compra.producto.nombre }}</td>
            <td>{{ compra.cantidad }} (kg)</td>
            <td>{{ compra.producto.proveedor }}</td>
            <td>{{ compra.total_pagado }} UYU</td>
            <td>{{ compra.fecha }}</td>
            <td>
              <div style="display: flex; gap: 0.5rem; align-items: center;">
                <a href="{% url 'stock_app:anulate_compra' compra.id %}"
                  class="button tiny clear"
                  style="color: red;">
                  Anular
                </a>
                <a href="{% url 'stock_app:detail_compra' compra.id %}"
                  class="button tiny clear"
                  style="color: rgb(127, 127, 17);">
                  Ver Detalles
                </a>
              </div>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="6" class="text-center">
              No hay Compras registradas.
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="grid-x align-justify" style="margin-top: 1.5rem;">
        <a href="{% url 'stock_app:Inicio' %}"
           class="button hollow secondary">
          Volver
        </a>
      </div>

      <div class="cell">
        {% if is_paginated %}
          <nav aria-label="Pagination">
            <ul class="pagination text-center">

              {% if page_obj.has_previous %}
                <li class="pagination-previous">
                  <a href="?page={{ page_obj.previous_page_number }}">Atrás</a>
                </li>
              {% endif %}

              {% for pagina in paginator.page_range %}
                <li class="{% if page_obj.number == pagina %}current{% endif %}">
                  <a href="?page={{ pagina }}">{{ pagina }}</a>
                </li>
              {% endfor %}

              {% if page_obj.has_next %}
                <li class="pagination-next">
                  <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                </li>
              {% endif %}

            </ul>
          </nav>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/stock/list_all_producto.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/header2.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x">
    <div class="cell small-12">

      <h2 class="text-center" style="margin: 1.5rem 0;">
        Listado Stock
      </h2>
      <form method="get" class="grid-x grid-margin-x">

        <div class="cell large-8">
          <input type="text" name="kword" id="kword" placeholder="Buscar por Nombre o tipo (mp, pt, sc)"
            class="no-margin-bottom">
          <div class="grid-x grid-margin-x align-bottom">
            <div class="cell medium-9">
              <input type="number" name="id" id="id" placeholder="Buscar por ID"
                class="no-margin-bottom">
            </div>
            <div class="cell medium-3">
              <button
                type="submit"
                class="button success expanded"
                style="height: 39px;">
                Buscar
              </button>
            </div>
          </div>
        </div>
      </form>

      <table class="hover unstriped">
        <thead>
          <tr>
            <th width="50">ID</th>
            <th>Nombre</th>
            <th>Tipo</th>
            <th>Precio (compra/producción)</th>
            <th>Proveedor</th>
            <th width="150">Clasificacion</th>
            <th width="150">Stock Actual</th>
            <th width="150" class="text-center">Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for materia in object_list %}
          
          {% if materia.tipo == 'PT' %}
            <tr>
            <td>{{ materia.id }}</td>
            <td>{{ materia.nombre }}</td>
            <td>{{ materia.tipo }}</td>
            <td>{{ materia.costo_calculado|floatformat:1 }} UYU | xkg</td>
            <td>{{ materia.proveedor }}</td>
            <td>{{ materia.clasificacion }}</td>
            <td>{{ materia.stock_actual }}kg</td>
            <td>
              <div style="display: flex; gap: 0.5rem; align-items: center;">
                <a href="{% url 'stock_app:detail_producto' materia.id %}"
                  class="button tiny clear"
                  style="color: green;">
                  Ver Detalles
                </a>
                <a href="{% url 'stock_app:delete_producto' materia.id %}"
                  class="button tiny clear"
                  style="color: red;">
                  Eliminar
                </a>
                <a href="{% url 'stock_app:update_producto' materia.id %}"
                  class="button tiny clear"
                  style="color: rgb(127, 127, 17);">
                  Editar
                </a>
                <a href="{% url 'stock_app:add_consumo' materia.id %}">
                  <button class="button tiny clear" style="color: rgb(17, 127, 127);">
                    Registrar Consumo
                  </button>
                </a>
              </div>
            </td>
          </tr>
          {% else %}
            <tr>
            <td>{{ materia.id }}</td>
            <td>{{ materia.nombre }}</td>
            <td>{{ materia.tipo }}</td>
            <td>{{ materia.precio|floatformat:1 }} UYU | xkg</td>
            <td>{{ materia.proveedor }}</td>
            <td>{{ materia.clasificacion }}</td>
            <td>{{ materia.stock_actual }}kg</td>
            <td>
              <div style="display: flex; gap: 0.5rem; align-items: center;">
                <a href="{% url 'stock_app:detail_producto' materia.id %}"
                  class="button tiny clear"
                  style="color: green;">
                  Ver Detalles
                </a>
                <a href="{% url 'stock_app:delete_producto' materia.id %}"
                  class="button tiny clear"
                  style="color: red;">
                  Eliminar
                </a>
                <a href="{% url 'stock_app:update_producto' materia.id %}"
                  class="button tiny clear"
                  style="color: rgb(127, 127, 17);">
                  Editar
                </a>
                <a href="{% url 'stock_app:add_compra' materia.id %}">
                  <button class="button tiny clear" style="color: rgb(17, 127, 127);">
                    Registrar Compra
                  </button>
                </a>
              </div>
            </td>
          </tr>
          {% endif %}
            
          {% empty %}
          <tr>
            <td colspan="6" class="text-center">
              No hay Materia Prima registrada.
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="grid-x align-justify" style="margin-top: 1.5rem;">
        <a href="{% url 'stock_app:Inicio' %}"
           class="button hollow secondary">
          Volver
        </a>
        <a href="{% url 'stock_app:add_producto' %}"
           class="button hollow primary">
          Registrar Materia
        </a>
      </div>

      <div class="cell">
        {% if is_paginated %}
          <nav aria-label="Pagination">
            <ul class="pagination text-center">

              {% if page_obj.has_previous %}
                <li class="pagination-previous">
                  <a href="?page={{ page_obj.previous_page_number }}">Atrás</a>
                </li>
              {% endif %}

              {% for pagina in paginator.page_range %}
                <li class="{% if page_obj.number == pagina %}current{% endif %}">
                  <a href="?page={{ pagina }}">{{ pagina }}</a>
                </li>
              {% endfor %}

              {% if page_obj.has_next %}
                <li class="pagination-next">
                  <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                </li>
              {% endif %}

            </ul>
          </nav>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/stock/list_all_proveedor.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/header2.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x">
    <div class="cell small-12">

      <h2 class="text-center" style="margin: 1.5rem 0;">
        Listado de Proveedores
      </h2>
      <form method="get" class="grid-x grid-margin-x">

        <div class="cell large-8">
          <input type="text" name="kword" id="kword" placeholder="Buscar por Nombre de proveedor">
          <div class="grid-x grid-margin-x align-bottom">
            <div class="cell medium-9">
              <input type="number" name="id" id="id" placeholder="Buscar por ID"
                class="no-margin-bottom">
            </div>
            <div class="cell medium-3">
              <button
                type="submit"
                class="button success expanded"
                style="height: 39px;">
                Buscar
              </button>
            </div>
          </div>
        </div>
      </form>

      <table class="hover unstriped">
        <thead>
          <tr>
            <th width="50">ID</th>
            <th>Nombre</th>
            <th>Numero</th>
            <th>Activo</th>
            <th width="150" class="text-center">Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for proveedor in object_list %}
          <tr>
            <td>{{ proveedor.id }}</td>
            <td>{{ proveedor.nombre }}</td>
            <td>{{ proveedor.num_contacto }}</td>
            <td>{{ proveedor.activo }}</td>
            <td>
              <div style="display: flex; gap: 0.5rem; align-items: center;">
                <a href="{% url 'stock_app:detail_proveedor' proveedor.id %}"
                  class="button tiny clear"
                  style="color: green;">
                  Ver Detalles
                </a>
                <a href="{% url 'stock_app:delete_proveedor' proveedor.id %}"
                  class="button tiny clear"
                  style="color: red;">
                  Eliminar
                </a>
                <a href="{% url 'stock_app:update_proveedor' proveedor.id %}"
                  class="button tiny clear"
                  style="color: rgb(127, 127, 17);">
                  Editar
                </a>
              </div>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="6" class="text-center">
              No hay Proveedores Registrados.
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="grid-x align-justify" style="margin-top: 1.5rem;">
        <a href="{% url 'stock_app:Inicio' %}"
           class="button hollow secondary">
          Volver
        </a>
        <a href="{% url 'stock_app:add_proveedor' %}"
           class="button hollow primary">
          Registrar Proveedor
        </a>
      </div>

      <div class="cell">
        {% if is_paginated %}
          <nav aria-label="Pagination">
            <ul class="pagination text-center">

              {% if page_obj.has_previous %}
                <li class="pagination-previous">
                  <a href="?page={{ page_obj.previous_page_number }}">Atrás</a>
                </li>
              {% endif %}

              {% for pagina in paginator.page_range %}
                <li class="{% if page_obj.number == pagina %}current{% endif %}">
                  <a href="?page={{ pagina }}">{{ pagina }}</a>
                </li>
              {% endfor %}

              {% if page_obj.has_next %}
                <li class="pagination-next">
                  <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                </li>
              {% endif %}

            </ul>
          </nav>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock content %}